### ISSUE TITLE
Feature request: Include in GeneticVariation or register as standalone package

### ISSUE THREAD

**Issue by MillironX** [BioJulia/SequenceVariation.jl#8]
I've found this project to be extremely useful, and would love to have it formalized.

Some updates to [my previous Discourse post](https://discourse.julialang.org/t/sequencevariation-brainstorming-for-new-package/66918/4):

This project _might_ be under the scope of https://github.com/BioJulia/GeneticVariation.jl, if GeneticVariation.jl changes its scope from an "all-in-one" package to a "biological entity" package. What I mean is:

Most of the BioJulia packages split functionality between a "biological entity" package and a "file format" package that references one or more "biological entity" package.

Examples:
| Entity                                 | File Format |
| -------------------------------------- | ----------- |
| https://github.com/BioJulia/BioSequences.jl    | https://github.com/BioJulia/FASTX.jl |
| https://github.com/BioJulia/BioAlignments.jl   | https://github.com/BioJulia/XAM.jl |
| https://github.com/BioJulia/GenomicFeatures.jl | https://github.com/BioJulia/GFF3.jl|

I didn't like this at first, but I've come to appreciate the design a lot. Basically, what I would propose is:

1. Convert GeneticVariation.jl to a "biological entity" package, i.e. remove all VCF/BCF parsing from the package
2. Update GeneticVariation.jl to Julia 1.6+, BioSequences 2+, etc.
3. Incorporate this project (https://github.com/jakobnissen/SequenceVariation.jl) into GeneticVariation.jl
4. Update https://github.com/rasmushenningsson/VariantCallFormat.jl to reference GeneticVariation.jl

I understand this proposal affects a lot of BioJulia, but I wasn't sure where else to put it. cc: @jakobnissen @rasmushenningsson @SabrinaJaye @kescobo

If it isn't desired to incorporate SequenceVariation.jl into GeneticVariation.jl, or if it will take a long time to do, I would still like to see it published as a standalone package.

**Comment by kescobo** [comment]
I have never thought of it that way, but now that you point it out, I think it has a lot of merit. I personally like the separation, because in some (many) cases, there are lots of different file formats to represent the same kind of info (eg you can use a multi FASTA to represent an alignment).

Should VariantCallFormat.jl be renamed XCF.jl to fit the theme of FASTX.jl and XAM.jl?

There are pluses and minuses to pulling things into BioJulia. On the pro side, discoverability and (in principle) a larger community of maintainers. On the con side, BioJulia is already pretty sprawling and too much for the maintainers we have. 

I think the pros outweigh the cons - I don't think the added maintenance burden will affect us on margin, but I would also totally understand if others disagree.

**Comment by MillironX** [comment]
> Should VariantCallFormat.jl be renamed XCF.jl to fit the theme of FASTX.jl and XAM.jl?

Maybe, but that was already changed once https://github.com/JuliaRegistries/General/pull/30036#issuecomment-778750374

**Comment by jakobnissen** [comment]
So I made this package about a year and a half ago, because I at the time worked with genetic variation of influenza sequences. To my great surprise, there was no easy way to make simple queries like "is mutation A relative to sequence B present in sequence C relative to sequence B". There were simply no vocabulary for it.

The idea was to make a small, standalone package that would define types that recorded the basic concept of a biological sequence variation, initially contained to indels and substitutions, but theoretically it could also be expanded to e.g. inversions.
This package could then be used as a dependency for other higher level packages that operated on sequence variation.

That is, if `GeneticVariation` is analogous to `BioSequences`, and `VariantCallFormat` is analogous to `FASTX`, then `SequenceVariation` would be analogous to `BIoSymbols`.

I still think that was a good idea. I just never really got the package going, and I'm not sure I nailed the interface. That's why this package is still half-baked, and not in BioJulia or the General Registry.

Now the situation is I've changed my job and no longer works with sequence variation. I have also got my todo-list filled with about a dozen other packages to work on, so I'm 90% confident I won't find the time to work on this.

That being said, I'd like to see the idea go forward. If anyone is willing to step up as the main developer, we can move this package to BioJulia, give them write permissions (or ownership), and mark it as work in progress.

**Comment by rasmushenningsson** [comment]
I decided to move the VCF parser from [GeneticVariation.jl](https://github.com/BioJulia/GeneticVariation.jl) out into a separate package [VariantCallFormat.jl](https://github.com/rasmushenningsson/VariantCallFormat.jl) some time ago.

My reasons for doing were roughly the following:

* I needed only VCF parsing and not the other features in GeneticVariation.jl.
* GeneticVariation.jl had several dependencies that were stuck on old versions.
* It's easier to maintain a well-defined package.

@MillironX I agree with your goal, but I'm not sure how to get there.
VCF files have many uses - I worked with paired tumor/normal cancer samples - which is a pretty different from population genetics. I don't want to load my variants into types that are designed for population genetics, but awkward for my use case. In that case I rather work with the data coming directly from the parser.

I guess I don't know how a "biological entity" package should be designed. (But I do want one. :slightly_smiling_face:)

**Comment by MillironX** [comment]
@jakobnissen 

> I'm not sure I nailed the interface

Fair enough, but SequenceVariation.jl is far more consistent and performant than anything I've come up with. That's what a pre-release version number is for, anyway, right?

> I've changed my job and no longer works with sequence variation ... If anyone is willing to step up as the main developer...

I'm more than willing to work on the package. I should be working with sequence variation for about the next year. :crossed_fingers: I'm not sure what's entailed in having write permissions in BioJulia, but I am willing to step up and try.

**Comment by kescobo** [comment]
>'m not sure what's entailed in having write permissions in BioJulia

My heuristic has been "They're willing to take some responsibility? Give them the bit!"

**Comment by MillironX** [comment]
@rasmushenningsson 

Yeah, a general-purpose VCF-to-`Variant` parser is almost impossible thanks to the variety of entities that VCF records can represent. I really appreciate your separation, and VariantCallFormat *is* well-defined and well-maintained, so let's not fix what ain't broke there.

**Comment by jakobnissen** [comment]
> I'm more than willing to work on the package. I should be working with sequence variation for about the next year. crossed_fingers I'm not sure what's entailed in having write permissions in BioJulia, but I am willing to step up and try.

That sounds fantastic. I'll put this repo in BioJulia, then make you the admin of it. Don't worry if maintaining this package doesn't work out, it wouldn't have worked out with me as the maintainer, so we are no worse off for trying even if it goes wrong.

**Comment by MillironX** [comment]
Hi @jakobnissen. Is there anything I need to do to move forward on this?
